### ISSUE TITLE
Custom emoticons

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/decent#18] opened 2017-12-03 14:28 UTC
Defined on the server. This will require uploading images - ping @eq since you've done a bunch of image uploading service work before! :tada:

~~No 50-emote limit, but maybe there should still be *some* limit -- does 500 seem reasonable? :)~~

**Comment by heyitsmeuralex** [comment] 2017-12-03 14:47
How about a default emoji set of some kind..?

i.e. if something sends literally the `thinking` emoji unicode character what happens to it? The problem is many browser+os combinations don't really handle emoji that well:

![image](https://user-images.githubusercontent.com/9429556/33526416-d1fb178a-d838-11e7-9d2b-88595e90ee81.png)

I don't think forcing a download of a bunch of emoji is particularly worth it, but we need to discuss this.

**Comment by heyitsmeuralex** [comment] 2017-12-03 14:49
I think it'd be nice to _not_ have a default set but allow admins to define unicode aliases for emoticons they upload themselves.

i.e. if I upload a `:blobthinking:` emoji, I should be able to assign it to the literal :thinking: unicode character, so I see thinking as :blobthinking: images.

**Comment by towerofnix** [comment] 2017-12-03 14:51
>I think it'd be nice to *not* have a default set but allow admins to define unicode aliases for emoticons they upload themselves.

That's a pretty cool idea! I do think there should still be a way to add separate emoticons, though - I don't think there's a unicode emoji which would match `:gnu_slash_thinking:` very well. (Besides :thinking:, I suppose, but what if I want `:gnu_slash_thinking:` *and* `:blobthinking:`?)

**Comment by heyitsmeuralex** [comment] 2017-12-03 14:52
Oh, of course. You don't _have_ to define the alias!

**Comment by heyitsmeuralex** [comment] 2017-12-03 19:18
So what's the census here?

Default set or no?

**Comment by heyitsmeuralex** [comment] 2017-12-03 19:18
>does 500 seem reasonable? :)

surely the owner of the server -- the admins!! -- should be able to decide that

**Comment by towerofnix** [comment] 2017-12-03 19:23
My opinion is to have a default set - so that people discover the feature - but have it be really, really easy to remove the emojis from that.

>surely the owner of the server -- the admins!! -- should be able to decide that

Sure; default to 500, have a toggle to let there be no limit, which only the server owner can change. (Hum, that means adding a new permission level. But having an owner level makes sense anyways.)

**Comment by heyitsmeuralex** [comment] 2017-12-03 20:28
>owner level

Why?

Owner has access to the CLI - that's ownership enough.

**Comment by towerofnix** [comment] 2017-12-03 20:35
Okay fine, yes.

I think a limit is plain unnecessary, since only admins can add emotes (and, presumably, those admins are trusted people).

**Comment by TheInitializer** [comment] 2017-12-03 22:01
I mean, this is decentralized, so the admins are either the owner of the server, or trusted by the owner of the server. So a limit seems unnecessary.

---

by "default set" do you mean a few custom emotes as default (i.e. what Slack does) or replacing each unicode emote with an image for consistency across platforms? (Slack also does this, as does Discord)

If we're doing the latter, make sure to have an option to turn that completely off (as in, don't download the images at all).

**Comment by heyitsmeuralex** [comment] 2017-12-06 00:07
Blocked by #67.

**Comment by heyitsmeuralex** [comment] 2017-12-21 20:35
Uploads and general settings UI are done - now is the time to do this 🌮

**Comment by heyitsmeuralex** [comment] 2017-12-22 12:26
![image](https://user-images.githubusercontent.com/9429556/34298007-65daf054-e713-11e7-9258-7d37439b782e.png)

**Comment by PullJosh** [comment] 2017-12-22 15:36
When we implement it, can we make our announcement be less juvenile? Thanks.

**Comment by heyitsmeuralex** [comment] 2017-12-23 17:09
Note that #135 does not implement the 'unicode alias' thing since we haven't come to a conclusion on how that'll work yet.

**Comment by TheInitializer** [comment] 2017-12-23 17:39
>Discord just added animated GIF emoji.

Slack has had that for a long time 📦

**Comment by heyitsmeuralex** [comment] 2017-12-23 17:45
Yup, and with Discord you need nitro to use them. Brilliant 🎉 

<h6>I'm pretty sure /api/image-upload takes image/gif so we should support em out of the box</h6>

**Closed** 2017-12-24 02:56 UTC
Labels: backend, client, has pr, warrants discussion
